chore(ci): move accuracy reporting commits to pull requests (#14)
* chore(ci): move accuracy reporting commits to pull requests

* chore: make sure we're not detached?

* chore: make sure we're not detached? pt2

* chore: make sure we're not detached? pt3

* chore: make sure we're not detached? pt4

* chore: make sure we're not detached? pt5

* chore: make sure we're not detached? pt6

* chore: update accuracy reports

* chore: cache reccmp install

* chore: cache reccmp install pt2

* chore: update accuracy reports

* chore: nevermind ignore for now

* chore: update accuracy reports

---------

Co-authored-by: github-actions <github-actions@github.com>

diff --git a/.github/workflows/build-and-report.yml b/.github/workflows/build-and-report.yml
--- a/.github/workflows/build-and-report.yml
+++ b/.github/workflows/build-and-report.yml
@@ -20,25 +20,6 @@ jobs:
     name: Download original binary
     uses: ./.github/workflows/cmr2bin.yml
 
-  # build:
-  #   name: Compile Visual Studio project with MSBuild
-  #   needs: [fetch-deps]
-  #   runs-on: "windows-latest"
-  #   steps:
-  #     - uses: actions/checkout@main
-  #     - name: Build
-  #       shell: cmd
-  #       run: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && msbuild /p:Platform=x86' }}
-  #       working-directory: CMR2Decomp
-
-  #     - name: Upload Artifact
-  #       uses: actions/upload-artifact@main
-  #       with:
-  #         name: Win32
-  #         path: |
-  #           CMR2Decomp/Debug/CMR2.exe
-  #           CMR2Decomp/Debug/CMR2.pdb
-
   build:
     name: Build (MSVC 6.0)
     needs: [fetch-deps]
@@ -74,6 +55,8 @@ jobs:
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@main
+        with:
+          ref: ${{ github.head_ref }}
 
       - uses: actions/setup-python@v5
         with:
@@ -92,20 +75,36 @@ jobs:
           path: cmr2bin
           key: cmr2bin
 
-      - name: Install python packages
+      - name: Install reccmp
         shell: bash
         run: |
           pip install git+https://github.com/isledecomp/reccmp
+
+      # - name: Restore cached reccmp install
+      #   id: cache-reccmp-install
+      #   uses: actions/cache/restore@v4
+      #   with:
+      #     enableCrossOsArchive: true
+      #     path: reccmp-python-package
+      #     key: reccmp-python-package
+
+      # - name: Install reccmp python package
+      #   if: ${{ !steps.cache-reccmp-install.outputs.cache-hit }}
+      #   run: |
+      #     pip install git+https://github.com/isledecomp/reccmp
+
+      # - name: Cache reccmp install
+      #   if: ${{ !steps.cache-reccmp-install.outputs.cache-hit }}
+      #   uses: actions/cache/save@v4
+      #   with:
+      #     enableCrossOsArchive: true
+      #     path: reccmp-python-package
+      #     key: reccmp-python-package
+
       - name: Detect binary
         run: |
           reccmp-project detect --what original   --search-path cmr2bin
           reccmp-project detect --what recompiled --search-path build
-
-      - name: Generate Accuracy Report
-        if: github.ref == 'refs/heads/main' # Only runs on main branch
-        shell: bash
-        run: |
-          reccmp-reccmp --target CMR2 --html index.html --json CMR2PROGRESS/summary.json
 
       - name: Compare Accuracy to main
         if: github.ref != 'refs/heads/main' # Only runs on pull requests
@@ -117,7 +116,7 @@ jobs:
           curl -fLSs -o summary-old.json $RELEASE_URL/summary.json || echo "" >summary-old.json
 
           # Compare with current main
-          reccmp-reccmp --target CMR2 --diff summary-old.json || echo "Current master not found"
+          reccmp-reccmp --target CMR2 --html index.html --json CMR2PROGRESS/summary.json --diff summary-old.json || echo "Current master not found"
 
       - name: Test Exports
         shell: bash
@@ -136,7 +135,7 @@ jobs:
           reccmp-datacmp --target CMR2
 
       - name: Commit Accuracy Reports
-        if: github.ref == 'refs/heads/main' # Only runs on the 'main' branch
+        if: github.ref != 'refs/heads/main' # Only runs on the 'main' branch
         shell: bash
         run: |
           git config user.name github-actions
