chore: fix workflow file pt11

diff --git a/.github/workflows/compare.yml b/.github/workflows/compare.yml
--- a/.github/workflows/compare.yml
+++ b/.github/workflows/compare.yml
@@ -53,7 +53,7 @@ jobs:
       - name: Install python packages
         shell: bash
         run: |
-          pip install -r tools/requirements.txt
+          pip install git+https://github.com/isledecomp/reccmp
       - name: Detect binary
         run: |
           reccmp-project detect --what original   --search-path cmr2bin
@@ -63,16 +63,16 @@ jobs:
         run: |
           reccmp-reccmp --target CMR2 --output index.html --json CMR2PROGRESS.json
 
-      - name: Compare Accuracy With Current Master
-        shell: bash
-        env:
-          RELEASE_URL: https://github.com/isledecomp/isle/releases/download/continuous
-        run: |
-          # Download the current master state
-          curl -fLSs -o CMR2PROGRESS-old.json $RELEASE_URL/CMR2PROGRESS.json || echo "" >CMR2PROGRESS-old.json
+      # - name: Compare Accuracy With Current Master
+      #   shell: bash
+      #   env:
+      #     RELEASE_URL: https://github.com/isledecomp/isle/releases/download/continuous
+      #   run: |
+      #     # Download the current master state
+      #     curl -fLSs -o CMR2PROGRESS-old.json $RELEASE_URL/CMR2PROGRESS.json || echo "" >CMR2PROGRESS-old.json
 
-          # Compare with current master
-          reccmp-reccmp --target CONFIG --diff CMR2PROGRESS-old.json || echo "Current master not found"
+      #     # Compare with current master
+      #     reccmp-reccmp --target CONFIG --diff CMR2PROGRESS-old.json || echo "Current master not found"
 
       - name: Test Exports
         shell: bash
